language: node_js
node_js:
  - "nodejs"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - npm run build
after_success:
  - npm pack
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "cso2-master-server-0.0.1.tgz"
  skip_cleanup: true
  on:
    tags: true